version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 3

  - package-ecosystem: pip
    directory: "/apps/backend"
    schedule:
      interval: weekly
      day: monday
    groups:
      backend-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: "/apps/mobile"
    schedule:
      interval: weekly
      day: monday
    groups:
      mobile-compatible-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 3

