import type { NutrientUnit } from "./types";

export const FDA_DAILY_VALUE_CATALOG_VERSION =
  "fda_daily_values_2016_v1" as const;

export const FDA_DAILY_VALUE_STANDARD =
  "FDA_NUTRITION_FACTS_ADULTS_AND_CHILDREN_4_PLUS" as const;

export type DriReferenceKind = "rda" | "ai" | "amdr" | "eer" | "cdrr";

export type FdaDailyValueReference = Readonly<{
  amount: string;
  unit: NutrientUnit;
  source_version: typeof FDA_DAILY_VALUE_CATALOG_VERSION;
  standard: typeof FDA_DAILY_VALUE_STANDARD;
}>;

export type CanonicalNutrientDefinition = Readonly<{
  id: string;
  display_name: string;
  default_unit: NutrientUnit;
  nutrient_kind: string;
  parent_nutrient_id: string | null;
  display_order: number;
  fda_daily_value: FdaDailyValueReference | null;
  dri_reference_kinds: readonly DriReferenceKind[];
}>;

export type NutrientRelationalSeedRow = readonly [
  id: string,
  displayName: string,
  nutrientKind: string,
  defaultUnit: NutrientUnit,
  parentNutrientId: string | null,
  displayOrder: number,
];

function dv(
  amount: string,
  unit: NutrientUnit,
): FdaDailyValueReference {
  return {
    amount,
    unit,
    source_version: FDA_DAILY_VALUE_CATALOG_VERSION,
    standard: FDA_DAILY_VALUE_STANDARD,
  };
}

export const NUTRIENT_CATALOG: readonly CanonicalNutrientDefinition[] = [
  {
    id: "calories",
    display_name: "Calories",
    default_unit: "kcal",
    nutrient_kind: "energy",
    parent_nutrient_id: null,
    display_order: 10,
    fda_daily_value: null,
    dri_reference_kinds: ["eer"],
  },
  {
    id: "total_fat",
    display_name: "Total Fat",
    default_unit: "g",
    nutrient_kind: "macro",
    parent_nutrient_id: null,
    display_order: 20,
    fda_daily_value: dv("78", "g"),
    dri_reference_kinds: ["amdr"],
  },
  {
    id: "saturated_fat",
    display_name: "Saturated Fat",
    default_unit: "g",
    nutrient_kind: "macro",
    parent_nutrient_id: "total_fat",
    display_order: 21,
    fda_daily_value: dv("20", "g"),
    dri_reference_kinds: [],
  },
  {
    id: "trans_fat",
    display_name: "Trans Fat",
    default_unit: "g",
    nutrient_kind: "macro",
    parent_nutrient_id: "total_fat",
    display_order: 22,
    fda_daily_value: null,
    dri_reference_kinds: [],
  },
  {
    id: "cholesterol",
    display_name: "Cholesterol",
    default_unit: "mg",
    nutrient_kind: "other",
    parent_nutrient_id: null,
    display_order: 30,
    fda_daily_value: dv("300", "mg"),
    dri_reference_kinds: [],
  },
  {
    id: "sodium",
    display_name: "Sodium",
    default_unit: "mg",
    nutrient_kind: "mineral",
    parent_nutrient_id: null,
    display_order: 40,
    fda_daily_value: dv("2300", "mg"),
    dri_reference_kinds: ["ai", "cdrr"],
  },
  {
    id: "total_carbohydrate",
    display_name: "Total Carbohydrate",
    default_unit: "g",
    nutrient_kind: "macro",
    parent_nutrient_id: null,
    display_order: 50,
    fda_daily_value: dv("275", "g"),
    dri_reference_kinds: ["rda", "amdr"],
  },
  {
    id: "dietary_fiber",
    display_name: "Dietary Fiber",
    default_unit: "g",
    nutrient_kind: "macro",
    parent_nutrient_id: "total_carbohydrate",
    display_order: 51,
    fda_daily_value: dv("28", "g"),
    dri_reference_kinds: ["ai"],
  },
  {
    id: "total_sugars",
    display_name: "Total Sugars",
    default_unit: "g",
    nutrient_kind: "macro",
    parent_nutrient_id: "total_carbohydrate",
    display_order: 52,
    fda_daily_value: null,
    dri_reference_kinds: [],
  },
  {
    id: "added_sugars",
    display_name: "Added Sugars",
    default_unit: "g",
    nutrient_kind: "macro",
    parent_nutrient_id: "total_sugars",
    display_order: 53,
    fda_daily_value: dv("50", "g"),
    dri_reference_kinds: [],
  },
  {
    id: "protein",
    display_name: "Protein",
    default_unit: "g",
    nutrient_kind: "macro",
    parent_nutrient_id: null,
    display_order: 60,
    fda_daily_value: dv("50", "g"),
    dri_reference_kinds: ["rda", "amdr"],
  },
  {
    id: "vitamin_d",
    display_name: "Vitamin D",
    default_unit: "mcg",
    nutrient_kind: "vitamin",
    parent_nutrient_id: null,
    display_order: 70,
    fda_daily_value: dv("20", "mcg"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "calcium",
    display_name: "Calcium",
    default_unit: "mg",
    nutrient_kind: "mineral",
    parent_nutrient_id: null,
    display_order: 80,
    fda_daily_value: dv("1300", "mg"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "iron",
    display_name: "Iron",
    default_unit: "mg",
    nutrient_kind: "mineral",
    parent_nutrient_id: null,
    display_order: 90,
    fda_daily_value: dv("18", "mg"),
    dri_reference_kinds: ["rda"],
  },
  {
    id: "potassium",
    display_name: "Potassium",
    default_unit: "mg",
    nutrient_kind: "mineral",
    parent_nutrient_id: null,
    display_order: 100,
    fda_daily_value: dv("4700", "mg"),
    dri_reference_kinds: ["ai"],
  },
  {
    id: "magnesium",
    display_name: "Magnesium",
    default_unit: "mg",
    nutrient_kind: "mineral",
    parent_nutrient_id: null,
    display_order: 110,
    fda_daily_value: dv("420", "mg"),
    dri_reference_kinds: ["rda"],
  },

  {
    id: "vitamin_a",
    display_name: "Vitamin A",
    default_unit: "mcg RAE",
    nutrient_kind: "vitamin",
    parent_nutrient_id: null,
    display_order: 120,
    fda_daily_value: dv("900", "mcg RAE"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "vitamin_c",
    display_name: "Vitamin C",
    default_unit: "mg",
    nutrient_kind: "vitamin",
    parent_nutrient_id: null,
    display_order: 130,
    fda_daily_value: dv("90", "mg"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "vitamin_e",
    display_name: "Vitamin E",
    default_unit: "mg alpha-tocopherol",
    nutrient_kind: "vitamin",
    parent_nutrient_id: null,
    display_order: 140,
    fda_daily_value: dv("15", "mg alpha-tocopherol"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "vitamin_k",
    display_name: "Vitamin K",
    default_unit: "mcg",
    nutrient_kind: "vitamin",
    parent_nutrient_id: null,
    display_order: 150,
    fda_daily_value: dv("120", "mcg"),
    dri_reference_kinds: ["ai"],
  },
  {
    id: "thiamin",
    display_name: "Thiamin",
    default_unit: "mg",
    nutrient_kind: "vitamin",
    parent_nutrient_id: null,
    display_order: 160,
    fda_daily_value: dv("1.2", "mg"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "riboflavin",
    display_name: "Riboflavin",
    default_unit: "mg",
    nutrient_kind: "vitamin",
    parent_nutrient_id: null,
    display_order: 170,
    fda_daily_value: dv("1.3", "mg"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "niacin",
    display_name: "Niacin",
    default_unit: "mg NE",
    nutrient_kind: "vitamin",
    parent_nutrient_id: null,
    display_order: 180,
    fda_daily_value: dv("16", "mg NE"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "vitamin_b6",
    display_name: "Vitamin B6",
    default_unit: "mg",
    nutrient_kind: "vitamin",
    parent_nutrient_id: null,
    display_order: 190,
    fda_daily_value: dv("1.7", "mg"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "folate",
    display_name: "Folate",
    default_unit: "mcg DFE",
    nutrient_kind: "vitamin",
    parent_nutrient_id: null,
    display_order: 200,
    fda_daily_value: dv("400", "mcg DFE"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "vitamin_b12",
    display_name: "Vitamin B12",
    default_unit: "mcg",
    nutrient_kind: "vitamin",
    parent_nutrient_id: null,
    display_order: 210,
    fda_daily_value: dv("2.4", "mcg"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "biotin",
    display_name: "Biotin",
    default_unit: "mcg",
    nutrient_kind: "vitamin",
    parent_nutrient_id: null,
    display_order: 220,
    fda_daily_value: dv("30", "mcg"),
    dri_reference_kinds: ["ai"],
  },
  {
    id: "pantothenic_acid",
    display_name: "Pantothenic Acid",
    default_unit: "mg",
    nutrient_kind: "vitamin",
    parent_nutrient_id: null,
    display_order: 230,
    fda_daily_value: dv("5", "mg"),
    dri_reference_kinds: ["ai"],
  },
  {
    id: "choline",
    display_name: "Choline",
    default_unit: "mg",
    nutrient_kind: "other",
    parent_nutrient_id: null,
    display_order: 240,
    fda_daily_value: dv("550", "mg"),
    dri_reference_kinds: ["ai"],
  },
  {
    id: "phosphorus",
    display_name: "Phosphorus",
    default_unit: "mg",
    nutrient_kind: "mineral",
    parent_nutrient_id: null,
    display_order: 250,
    fda_daily_value: dv("1250", "mg"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "iodine",
    display_name: "Iodine",
    default_unit: "mcg",
    nutrient_kind: "mineral",
    parent_nutrient_id: null,
    display_order: 260,
    fda_daily_value: dv("150", "mcg"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "zinc",
    display_name: "Zinc",
    default_unit: "mg",
    nutrient_kind: "mineral",
    parent_nutrient_id: null,
    display_order: 270,
    fda_daily_value: dv("11", "mg"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "selenium",
    display_name: "Selenium",
    default_unit: "mcg",
    nutrient_kind: "mineral",
    parent_nutrient_id: null,
    display_order: 280,
    fda_daily_value: dv("55", "mcg"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "copper",
    display_name: "Copper",
    default_unit: "mg",
    nutrient_kind: "mineral",
    parent_nutrient_id: null,
    display_order: 290,
    fda_daily_value: dv("0.9", "mg"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "manganese",
    display_name: "Manganese",
    default_unit: "mg",
    nutrient_kind: "mineral",
    parent_nutrient_id: null,
    display_order: 300,
    fda_daily_value: dv("2.3", "mg"),
    dri_reference_kinds: ["ai"],
  },
  {
    id: "chromium",
    display_name: "Chromium",
    default_unit: "mcg",
    nutrient_kind: "mineral",
    parent_nutrient_id: null,
    display_order: 310,
    fda_daily_value: dv("35", "mcg"),
    dri_reference_kinds: ["ai"],
  },
  {
    id: "molybdenum",
    display_name: "Molybdenum",
    default_unit: "mcg",
    nutrient_kind: "mineral",
    parent_nutrient_id: null,
    display_order: 320,
    fda_daily_value: dv("45", "mcg"),
    dri_reference_kinds: ["rda", "ai"],
  },
  {
    id: "chloride",
    display_name: "Chloride",
    default_unit: "mg",
    nutrient_kind: "mineral",
    parent_nutrient_id: null,
    display_order: 330,
    fda_daily_value: dv("2300", "mg"),
    dri_reference_kinds: ["ai"],
  },

  {
    id: "total_omega_3",
    display_name: "Omega-3",
    default_unit: "mg",
    nutrient_kind: "fatty_acid",
    parent_nutrient_id: null,
    display_order: 390,
    fda_daily_value: null,
    dri_reference_kinds: [],
  },
  {
    id: "alpha_linolenic_acid",
    display_name: "Alpha-Linolenic Acid (ALA)",
    default_unit: "g",
    nutrient_kind: "fatty_acid",
    parent_nutrient_id: "total_omega_3",
    display_order: 400,
    fda_daily_value: null,
    dri_reference_kinds: ["ai", "amdr"],
  },
  {
    id: "epa",
    display_name: "EPA",
    default_unit: "mg",
    nutrient_kind: "fatty_acid",
    parent_nutrient_id: "total_omega_3",
    display_order: 410,
    fda_daily_value: null,
    dri_reference_kinds: [],
  },
  {
    id: "dha",
    display_name: "DHA",
    default_unit: "mg",
    nutrient_kind: "fatty_acid",
    parent_nutrient_id: "total_omega_3",
    display_order: 420,
    fda_daily_value: null,
    dri_reference_kinds: [],
  },
  {
    id: "linoleic_acid",
    display_name: "Linoleic Acid (Omega-6)",
    default_unit: "g",
    nutrient_kind: "fatty_acid",
    parent_nutrient_id: null,
    display_order: 430,
    fda_daily_value: null,
    dri_reference_kinds: ["ai", "amdr"],
  },
];

export const NUTRIENT_CATALOG_BY_ID = new Map(
  NUTRIENT_CATALOG.map((nutrient) => [nutrient.id, nutrient] as const),
);

export const NUTRIENT_RELATIONAL_SEED_ROWS:
readonly NutrientRelationalSeedRow[] = NUTRIENT_CATALOG.map(
  (nutrient) => [
    nutrient.id,
    nutrient.display_name,
    nutrient.nutrient_kind,
    nutrient.default_unit,
    nutrient.parent_nutrient_id,
    nutrient.display_order,
  ] as const,
);
