from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from typing import Any


FDA_DAILY_VALUE_CATALOG_VERSION = "fda_daily_values_2016_v1"
FDA_DAILY_VALUE_STANDARD = "FDA_NUTRITION_FACTS_ADULTS_AND_CHILDREN_4_PLUS"

DRI_REFERENCE_KINDS = frozenset({"rda", "ai", "amdr", "eer", "cdrr"})


@dataclass(frozen=True)
class FdaDailyValueReference:
    amount: Decimal
    unit: str
    source_version: str = FDA_DAILY_VALUE_CATALOG_VERSION
    standard: str = FDA_DAILY_VALUE_STANDARD


@dataclass(frozen=True)
class NutrientDefinition:
    id: str
    display_name: str
    default_unit: str
    nutrient_kind: str
    parent_nutrient_id: str | None
    display_order: int
    fda_daily_value: FdaDailyValueReference | None = None
    dri_reference_kinds: tuple[str, ...] = ()


def _dv(amount: str, unit: str) -> FdaDailyValueReference:
    return FdaDailyValueReference(Decimal(amount), unit)


NUTRIENT_CATALOG: tuple[NutrientDefinition, ...] = (
    NutrientDefinition(
        "calories",
        "Calories",
        "kcal",
        "energy",
        None,
        10,
        dri_reference_kinds=("eer",),
    ),
    NutrientDefinition(
        "total_fat",
        "Total Fat",
        "g",
        "macro",
        None,
        20,
        _dv("78", "g"),
        ("amdr",),
    ),
    NutrientDefinition(
        "saturated_fat",
        "Saturated Fat",
        "g",
        "macro",
        "total_fat",
        21,
        _dv("20", "g"),
    ),
    NutrientDefinition(
        "trans_fat",
        "Trans Fat",
        "g",
        "macro",
        "total_fat",
        22,
    ),
    NutrientDefinition(
        "cholesterol",
        "Cholesterol",
        "mg",
        "other",
        None,
        30,
        _dv("300", "mg"),
    ),
    NutrientDefinition(
        "sodium",
        "Sodium",
        "mg",
        "mineral",
        None,
        40,
        _dv("2300", "mg"),
        ("ai", "cdrr"),
    ),
    NutrientDefinition(
        "total_carbohydrate",
        "Total Carbohydrate",
        "g",
        "macro",
        None,
        50,
        _dv("275", "g"),
        ("rda", "amdr"),
    ),
    NutrientDefinition(
        "dietary_fiber",
        "Dietary Fiber",
        "g",
        "macro",
        "total_carbohydrate",
        51,
        _dv("28", "g"),
        ("ai",),
    ),
    NutrientDefinition(
        "total_sugars",
        "Total Sugars",
        "g",
        "macro",
        "total_carbohydrate",
        52,
    ),
    NutrientDefinition(
        "added_sugars",
        "Added Sugars",
        "g",
        "macro",
        "total_sugars",
        53,
        _dv("50", "g"),
    ),
    NutrientDefinition(
        "protein",
        "Protein",
        "g",
        "macro",
        None,
        60,
        _dv("50", "g"),
        ("rda", "amdr"),
    ),
    NutrientDefinition(
        "vitamin_d",
        "Vitamin D",
        "mcg",
        "vitamin",
        None,
        70,
        _dv("20", "mcg"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "calcium",
        "Calcium",
        "mg",
        "mineral",
        None,
        80,
        _dv("1300", "mg"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "iron",
        "Iron",
        "mg",
        "mineral",
        None,
        90,
        _dv("18", "mg"),
        ("rda",),
    ),
    NutrientDefinition(
        "potassium",
        "Potassium",
        "mg",
        "mineral",
        None,
        100,
        _dv("4700", "mg"),
        ("ai",),
    ),
    NutrientDefinition(
        "magnesium",
        "Magnesium",
        "mg",
        "mineral",
        None,
        110,
        _dv("420", "mg"),
        ("rda",),
    ),
    NutrientDefinition(
        "vitamin_a",
        "Vitamin A",
        "mcg RAE",
        "vitamin",
        None,
        120,
        _dv("900", "mcg RAE"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "vitamin_c",
        "Vitamin C",
        "mg",
        "vitamin",
        None,
        130,
        _dv("90", "mg"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "vitamin_e",
        "Vitamin E",
        "mg alpha-tocopherol",
        "vitamin",
        None,
        140,
        _dv("15", "mg alpha-tocopherol"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "vitamin_k",
        "Vitamin K",
        "mcg",
        "vitamin",
        None,
        150,
        _dv("120", "mcg"),
        ("ai",),
    ),
    NutrientDefinition(
        "thiamin",
        "Thiamin",
        "mg",
        "vitamin",
        None,
        160,
        _dv("1.2", "mg"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "riboflavin",
        "Riboflavin",
        "mg",
        "vitamin",
        None,
        170,
        _dv("1.3", "mg"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "niacin",
        "Niacin",
        "mg NE",
        "vitamin",
        None,
        180,
        _dv("16", "mg NE"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "vitamin_b6",
        "Vitamin B6",
        "mg",
        "vitamin",
        None,
        190,
        _dv("1.7", "mg"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "folate",
        "Folate",
        "mcg DFE",
        "vitamin",
        None,
        200,
        _dv("400", "mcg DFE"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "vitamin_b12",
        "Vitamin B12",
        "mcg",
        "vitamin",
        None,
        210,
        _dv("2.4", "mcg"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "biotin",
        "Biotin",
        "mcg",
        "vitamin",
        None,
        220,
        _dv("30", "mcg"),
        ("ai",),
    ),
    NutrientDefinition(
        "pantothenic_acid",
        "Pantothenic Acid",
        "mg",
        "vitamin",
        None,
        230,
        _dv("5", "mg"),
        ("ai",),
    ),
    NutrientDefinition(
        "choline",
        "Choline",
        "mg",
        "other",
        None,
        240,
        _dv("550", "mg"),
        ("ai",),
    ),
    NutrientDefinition(
        "phosphorus",
        "Phosphorus",
        "mg",
        "mineral",
        None,
        250,
        _dv("1250", "mg"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "iodine",
        "Iodine",
        "mcg",
        "mineral",
        None,
        260,
        _dv("150", "mcg"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "zinc",
        "Zinc",
        "mg",
        "mineral",
        None,
        270,
        _dv("11", "mg"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "selenium",
        "Selenium",
        "mcg",
        "mineral",
        None,
        280,
        _dv("55", "mcg"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "copper",
        "Copper",
        "mg",
        "mineral",
        None,
        290,
        _dv("0.9", "mg"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "manganese",
        "Manganese",
        "mg",
        "mineral",
        None,
        300,
        _dv("2.3", "mg"),
        ("ai",),
    ),
    NutrientDefinition(
        "chromium",
        "Chromium",
        "mcg",
        "mineral",
        None,
        310,
        _dv("35", "mcg"),
        ("ai",),
    ),
    NutrientDefinition(
        "molybdenum",
        "Molybdenum",
        "mcg",
        "mineral",
        None,
        320,
        _dv("45", "mcg"),
        ("rda", "ai"),
    ),
    NutrientDefinition(
        "chloride",
        "Chloride",
        "mg",
        "mineral",
        None,
        330,
        _dv("2300", "mg"),
        ("ai",),
    ),
    NutrientDefinition(
        "alpha_linolenic_acid",
        "Alpha-Linolenic Acid (ALA)",
        "g",
        "fatty_acid",
        "total_fat",
        400,
        dri_reference_kinds=("ai", "amdr"),
    ),
    NutrientDefinition(
        "epa",
        "EPA",
        "mg",
        "fatty_acid",
        "total_fat",
        410,
    ),
    NutrientDefinition(
        "dha",
        "DHA",
        "mg",
        "fatty_acid",
        "total_fat",
        420,
    ),
    NutrientDefinition(
        "linoleic_acid",
        "Linoleic Acid (Omega-6)",
        "g",
        "fatty_acid",
        "total_fat",
        430,
        dri_reference_kinds=("ai", "amdr"),
    ),
)


def nutrient_seed_rows() -> list[dict[str, Any]]:
    """Return only columns persisted by the nutrients relational table."""
    return [
        {
            "id": nutrient.id,
            "display_name": nutrient.display_name,
            "default_unit": nutrient.default_unit,
            "nutrient_kind": nutrient.nutrient_kind,
            "parent_nutrient_id": nutrient.parent_nutrient_id,
            "display_order": nutrient.display_order,
        }
        for nutrient in NUTRIENT_CATALOG
    ]
